Feature/generation model
Nblyumenshteyn/TaskManager pull request #5
Opened 2021-04-22 19:06 UTC by Nblyumenshteyn

2021-04-22 20:07 UTC, greybutton requested changes

2021-04-22 20:07 UTC, greybutton commented on config/initializers/simple_form.rb
> +# frozen_string_literal: true
симпл форм рановато генерировать, он чуть позже добавится, давай уберем пока)
config/initializers/simple_form.rb
config/locales/simple_form.en.yml
lib/templates/erb/scaffold/_form.html.erb

2021-04-22 20:07 UTC, greybutton commented on test/factories/tasks.rb
> +    description { "MyText" }
под эти поля тоже можно сделать sequence

2021-04-22 20:07 UTC, greybutton commented on test/factories/users.rb
> +    avatar { 'MyString' }
под эти тоже

2021-04-22 20:29 UTC, Nblyumenshteyn commented on test/factories/users.rb
> +    avatar { 'MyString' }
поправила

2021-04-23 07:42 UTC, greybutton approved these changes

2021-04-23 10:48 UTC, merged